const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAIL = 'LOGIN_FAIL';
const LOGIN_LOADING = 'LOGIN_LOADING';

const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
const REGISTER_FAIL = 'REGISTER_FAIL';
const REGISTER_LOADING = 'REGISTER_LOADING';

const UPDATE_SUCCESS = 'UPDATE_SUCCESS';
const UPDATE_FAIL = 'UPDATE_FAIL';
const UPDATE_LOADING = 'UPDATE_LOADING';

const CHANGE_PASS_SUCCESS = 'CHANGE_PASS_SUCCESS';
const CHANGE_PASS_FAIL = 'CHANGE_PASS_FAIL';
const CHANGE_PASS_LOADING = 'CHANGE_PASS_LOADING';

const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS';
const UPLOAD_FAIL = 'UPLOAD_FAIL';
const UPLOAD_LOADING = 'UPLOAD_LOADING';

export {
  LOGIN_SUCCESS,
  LOGIN_FAIL,
  LOGIN_LOADING,
  REGISTER_SUCCESS,
  REGISTER_FAIL,
  REGISTER_LOADING,
  UPDATE_SUCCESS,
  UPDATE_FAIL,
  UPDATE_LOADING,
  CHANGE_PASS_SUCCESS,
  CHANGE_PASS_FAIL,
  CHANGE_PASS_LOADING,
  UPLOAD_SUCCESS,
  UPLOAD_FAIL,
  UPLOAD_LOADING,
};
